<a href="https://colab.research.google.com/github/iam-fern/Generate_data/blob/main/ex_sampling_c_1000rep_n30_x6_norm_sas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

import statistics as stats
import scipy.stats as ss
import scipy.stats as st
from scipy.stats import f_oneway
from scipy import stats
import scipy.stats as stats
import time
import statsmodels.api as sm

from statsmodels.formula.api import ols

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
df = pd.read_csv('https://github.com/iam-fern/Research/raw/main/sampling_1000rep_n30_x6_norm_sas.csv', index_col=['rep', 'index'])
df

                   x1        x2        x3  ...           Y      y_hat       e_hat
rep   index                                ...
0.0   0.0   -0.145753  0.257231 -0.975087  ...    2.824597   2.569186    0.255411
      1.0   -0.619013 -1.921037  0.201588  ...   -3.016132  -3.762423    0.746291
      2.0    0.305009 -0.187300 -0.343690  ...    7.518945   8.655529   -1.136584
      3.0    0.289985  0.386395  0.319321  ...    8.604700   8.778582   -0.173882
      4.0    0.649824  1.378676 -0.484742  ...   12.326924  13.490416   -1.163491
...               ...       ...       ...  ...         ...        ...         ...
999.0 25.0  -0.752511  1.062612  0.977830  ...   -0.295249  -4.698820    4.403571
      26.0  -0.324877  0.630567  0.346713  ...    2.727033   0.685311    2.041722
      27.0  -2.146727 -0.248251 -1.012751  ...  150.348226 -24.065500  174.413727
      28.0   0.589368  2.532500 -0.176281  ...   13.258063  13.013862    0.244201
      29.0   1.203192  0.959954 -0.973880  ...   20.344905  20.588562   -0.243657

[30000 rows x 7 columns]

In [3]:
# ลบข้อมูลที่มี missing values
table = df.dropna()
table

                   x1        x2        x3  ...           Y      y_hat       e_hat
rep   index                                ...
0.0   0.0   -0.145753  0.257231 -0.975087  ...    2.824597   2.569186    0.255411
      1.0   -0.619013 -1.921037  0.201588  ...   -3.016132  -3.762423    0.746291
      2.0    0.305009 -0.187300 -0.343690  ...    7.518945   8.655529   -1.136584
      3.0    0.289985  0.386395  0.319321  ...    8.604700   8.778582   -0.173882
      4.0    0.649824  1.378676 -0.484742  ...   12.326924  13.490416   -1.163491
...               ...       ...       ...  ...         ...        ...         ...
999.0 25.0  -0.752511  1.062612  0.977830  ...   -0.295249  -4.698820    4.403571
      26.0  -0.324877  0.630567  0.346713  ...    2.727033   0.685311    2.041722
      27.0  -2.146727 -0.248251 -1.012751  ...  150.348226 -24.065500  174.413727
      28.0   0.589368  2.532500 -0.176281  ...   13.258063  13.013862    0.244201
      29.0   1.203192  0.959954 -0.973880  ...   20.344905  20.588562   -0.243657

[30000 rows x 7 columns]

In [4]:
table.reset_index(inplace=True)
table

         rep  index        x1  ...           Y      y_hat       e_hat
0        0.0    0.0 -0.145753  ...    2.824597   2.569186    0.255411
1        0.0    1.0 -0.619013  ...   -3.016132  -3.762423    0.746291
2        0.0    2.0  0.305009  ...    7.518945   8.655529   -1.136584
3        0.0    3.0  0.289985  ...    8.604700   8.778582   -0.173882
4        0.0    4.0  0.649824  ...   12.326924  13.490416   -1.163491
...      ...    ...       ...  ...         ...        ...         ...
29995  999.0   25.0 -0.752511  ...   -0.295249  -4.698820    4.403571
29996  999.0   26.0 -0.324877  ...    2.727033   0.685311    2.041722
29997  999.0   27.0 -2.146727  ...  150.348226 -24.065500  174.413727
29998  999.0   28.0  0.589368  ...   13.258063  13.013862    0.244201
29999  999.0   29.0  1.203192  ...   20.344905  20.588562   -0.243657

[30000 rows x 9 columns]

In [5]:
table.set_index(['rep', 'index'], inplace=True)

In [6]:
table

                   x1        x2        x3  ...           Y      y_hat       e_hat
rep   index                                ...
0.0   0.0   -0.145753  0.257231 -0.975087  ...    2.824597   2.569186    0.255411
      1.0   -0.619013 -1.921037  0.201588  ...   -3.016132  -3.762423    0.746291
      2.0    0.305009 -0.187300 -0.343690  ...    7.518945   8.655529   -1.136584
      3.0    0.289985  0.386395  0.319321  ...    8.604700   8.778582   -0.173882
      4.0    0.649824  1.378676 -0.484742  ...   12.326924  13.490416   -1.163491
...               ...       ...       ...  ...         ...        ...         ...
999.0 25.0  -0.752511  1.062612  0.977830  ...   -0.295249  -4.698820    4.403571
      26.0  -0.324877  0.630567  0.346713  ...    2.727033   0.685311    2.041722
      27.0  -2.146727 -0.248251 -1.012751  ...  150.348226 -24.065500  174.413727
      28.0   0.589368  2.532500 -0.176281  ...   13.258063  13.013862    0.244201
      29.0   1.203192  0.959954 -0.973880  ...   20.344905  20.588562   -0.243657

[30000 rows x 7 columns]

In [7]:
def get_result(run_replicate):
    new_table = table.loc[run_replicate]

    # show index
    new_table.reset_index(inplace=True)

    new_table.drop(['index'], axis=1, inplace=True)


    # แบ่งข้อมูลออกเป็น 2 กลุ่มด้วย k-mean

    #Set number of clusters
    x = new_table[["x1", "x2", "x3"]]
    k_means = KMeans(n_clusters=2)

    #Run the clustering algorithm
    model = k_means.fit(x)
    model

    #Generate cluster predictions and store in y_kmeans
    y_kmeans = k_means.predict(x)
    y_kmeans

    # kmean_clusters.astype(float)
    kmean_clusters = pd.DataFrame({"clusters" : y_kmeans})

    # เชื่อมข้อมูลทั้ง 2 DataFrame เข้าด้วยกันด้วยคำสั่ง pd.concat
    data_clusters = pd.concat([new_table, kmean_clusters], axis=1)

    data_sort_clusters = data_clusters.sort_values('clusters')

    # print(data_clusters.groupby('clusters').groups)

    data_sort_clusters.reset_index(inplace=True)

    # กลุ่มที่ 1
    data_cluster1 = data_sort_clusters[data_sort_clusters.clusters == 1]

    y = data_cluster1[['Y']]
    x = data_cluster1[['x1', 'x2', 'x3']]
    x = sm.add_constant(x)
    model1 = sm.OLS(y, x).fit()

    DF1 = model1.df_resid

    SSR1 = model1.ssr

    MSE1 = model1.mse_resid

    # กลุ่มที่ 2
    data_cluster0 = data_sort_clusters[data_sort_clusters.clusters == 0]

    y = data_cluster0[['Y']]
    x = data_cluster0[['x1', 'x2', 'x3']]
    x = sm.add_constant(x)
    model0 = sm.OLS(y, x).fit()

    DF0 = model0.df_resid

    SSR0 = model0.ssr

    MSE0 = model0.mse_resid

    df1 = DF1+1
    df0 = DF0+1

    # คำนวณค่าสถิติ
    GQ_test_clusters = (SSR1/df1) / (SSR0/df0)


    # คำนวณค่า p-value
    # sf(x, dfn, dfd, loc=0, scale=1) : Survival function (also defined as 1 - cdf, but sf is sometimes more accurate)
    two_tailed = 2.0*(1.0-(ss.f.cdf(GQ_test_clusters, df1, df0)))

    # pdf(x, dfn, dfd, loc=0, scale=1) : Probability density function
    p_greater = ss.f.cdf(GQ_test_clusters, df1, df0)
    
    return df0, df1, SSR0, SSR1, MSE0, MSE1, GQ_test_clusters, two_tailed, p_greater

# สร้าง list ของ replicates
list_replicate=list({i[0] for i in table.index})
list_replicate.sort()

# สร้าง list เพื่อเก็บค่า ทุกรอบที่ run
list_df0=[]
list_df1=[]
list_SSR0=[]
list_SSR1=[]
list_MSE0=[]
list_MSE1=[]
list_GQ_test_clusters=[]
list_result_test=[]
list_two_tailed=[]
list_p_greater=[]
list_result_test01=[]

# ใช้ for loop สำหรับการ run ทุก replicates
for run_replicate in list_replicate:
    df0, df1, SSR0, SSR1, MSE0, MSE1, GQ_test_clusters, two_tailed, p_greater=get_result(run_replicate)

    list_df0.append(df0)
    list_df1.append(df1)
    list_SSR0.append(SSR0)
    list_SSR1.append(SSR1)
    list_MSE0.append(MSE0)
    list_MSE1.append(MSE1)
    list_GQ_test_clusters.append(GQ_test_clusters)
    list_two_tailed.append(two_tailed)
    list_p_greater.append(p_greater)

/usr/local/lib/python3.7/dist-packages/statsmodels/regression/linear_model.py:1665: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid
/usr/local/lib/python3.7/dist-packages/statsmodels/regression/linear_model.py:1665: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid
/usr/local/lib/python3.7/dist-packages/statsmodels/regression/linear_model.py:1665: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid
/usr/local/lib/python3.7/dist-packages/statsmodels/regression/linear_model.py:1665: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid
/usr/local/lib/python3.7/dist-packages/statsmodels/regression/linear_model.py:1665: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid

In [8]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
two_tailed_new=pd.DataFrame({"Replicate":list_replicate, "df0":list_df0, "df1":list_df1, "SSR0":list_SSR0,
                     "SSR1":list_SSR1, "MSE0":list_MSE0, "MSE1":list_MSE1, 
                     "GQ_test_clusters":list_GQ_test_clusters, "two_tailed":list_two_tailed, "greater":list_p_greater})
two_tailed_new.set_index(['Replicate'], inplace=True)
two_tailed_new=two_tailed_new[(two_tailed_new["two_tailed"]<=1) & (two_tailed_new["greater"]<=1)]
two_tailed_new["Result_test"]=two_tailed_new["two_tailed"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                  if p_value < alpha else 'Reject005=1 : Homoscedasticity')
#two_tailed_new_show=two_tailed_new.drop(columns="greater")
two_tailed_new.astype(str)

            df0   df1                SSR0                SSR1                MSE0                MSE1    GQ_test_clusters              two_tailed             greater                       Result_test
Replicate
0.0         9.0  15.0  16.461917258361048   60182.95284671644   2.057739657295131   4298.782346194032   2193.533787183241   7.527312106958561e-14  0.9999999999999624  Reject005=0 : Heteroscedasticity
1.0        16.0   8.0   3172.919052502346  11783.760369381596  211.52793683348972  1683.3943384830852   7.427709421132724    0.000724682818091793  0.9996376585909541  Reject005=0 : Heteroscedasticity
2.0        13.0  11.0   737.4811251827632  1668.9064370097299   61.45676043189693    166.890643700973  2.6744331531504764     0.09502987079351843  0.9524850646032408    Reject005=1 : Homoscedasticity
12.0       12.0  12.0   81.39980046163313  491.73067563223145   7.399981860148467  44.702788693839224   6.040932199385465    0.003979189036817932   0.998010405481591  Reject005=0 : Heteroscedasticity
13.0       17.0   7.0  24915.225248476123   526621.8805656993  1557.2015780297577   87770.31342761655   51.33161912235314   6.695493048880508e-10  0.9999999996652253  Reject005=0 : Heteroscedasticity
...         ...   ...                 ...                 ...                 ...                 ...                 ...                     ...                 ...                               ...
992.0      17.0   7.0   3.486428130926056   250.9821945117441  0.2179017581828785   41.83036575195735   174.8288402289472   2.842170943040401e-14  0.9999999999999858  Reject005=0 : Heteroscedasticity
993.0      10.0  14.0   6352.192776279033   45851.78220374908    705.799197364337    3527.06016951916   5.155900356957185    0.013049939963915236  0.9934750300180424  Reject005=0 : Heteroscedasticity
995.0      16.0   8.0  15856.824615911415  17459.080041099354   1057.121641060761   2494.154291585622  2.2020903256481965      0.1703746029485358  0.9148126985257321    Reject005=1 : Homoscedasticity
996.0      18.0   6.0   18.34953337338264  3801616.5135947405   1.079384316081332   760323.3027189481   621533.4912727427   2.220446049250313e-16  0.9999999999999999  Reject005=0 : Heteroscedasticity
999.0      13.0  11.0  489.24856675909894  14182.683534796899   40.77071389659158    1418.26835347969    34.2593814416823  1.7935525575829558e-07  0.9999999103223721  Reject005=0 : Heteroscedasticity

[523 rows x 10 columns]

In [9]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
two_tailed_new=pd.DataFrame({"Replicate":list_replicate, "df0":list_df0, "df1":list_df1, "SSR0":list_SSR0,
                     "SSR1":list_SSR1, "MSE0":list_MSE0, "MSE1":list_MSE1,
                     "GQ_test_clusters":list_GQ_test_clusters, "two_tailed":list_two_tailed, "greater":list_p_greater})
two_tailed_new.set_index(['Replicate'], inplace=True)

two_tailed_new["two_tailed_new"]=two_tailed_new[["two_tailed","greater"]].apply(lambda value: value[0] if value[0]<0.5 else 2*value[1], axis=1)
two_tailed_new["Result_test"]=two_tailed_new["two_tailed_new"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                      if p_value < alpha else 'Reject005=1 : Homoscedasticity')


two_tailed_new_show=two_tailed_new.drop(columns=["two_tailed", "greater"])
two_tailed_new_show.astype(str)

            df0   df1                SSR0                SSR1                MSE0                 MSE1      GQ_test_clusters          two_tailed_new                       Result_test
Replicate
0.0         9.0  15.0  16.461917258361048   60182.95284671644   2.057739657295131    4298.782346194032     2193.533787183241   7.527312106958561e-14  Reject005=0 : Heteroscedasticity
1.0        16.0   8.0   3172.919052502346  11783.760369381596  211.52793683348972   1683.3943384830852     7.427709421132724    0.000724682818091793  Reject005=0 : Heteroscedasticity
2.0        13.0  11.0   737.4811251827632  1668.9064370097299   61.45676043189693     166.890643700973    2.6744331531504764     0.09502987079351843    Reject005=1 : Homoscedasticity
3.0        18.0   6.0   516.2794461610548  2.3813208349989012    30.3693791859444  0.47626416699978025  0.013837394763858419    3.10701037746153e-05  Reject005=0 : Heteroscedasticity
4.0        12.0  12.0   7778.236227060574   6338.372894568511    707.112384278234    576.2157176880464    0.8148856256791531      0.7286169563139095    Reject005=1 : Homoscedasticity
...         ...   ...                 ...                 ...                 ...                  ...                   ...                     ...                               ...
995.0      16.0   8.0  15856.824615911415  17459.080041099354   1057.121641060761    2494.154291585622    2.2020903256481965      0.1703746029485358    Reject005=1 : Homoscedasticity
996.0      18.0   6.0   18.34953337338264  3801616.5135947405   1.079384316081332    760323.3027189481     621533.4912727427   2.220446049250313e-16  Reject005=0 : Heteroscedasticity
997.0      17.0   7.0  15518.928659844945  372.78742492026817   969.9330412403091    62.13123748671136   0.05833784721458507   0.0008425165304940571  Reject005=0 : Heteroscedasticity
998.0       7.0  17.0  14390.444423295017   135.2496502094225   2398.407403882503    8.453103138088906  0.003870000870092812      1.074998187165e-15  Reject005=0 : Heteroscedasticity
999.0      13.0  11.0  489.24856675909894  14182.683534796899   40.77071389659158     1418.26835347969      34.2593814416823  1.7935525575829558e-07  Reject005=0 : Heteroscedasticity

[1000 rows x 9 columns]

In [10]:
two_tailed_new_show['Result_test'].value_counts()

Reject005=0 : Heteroscedasticity    766
Reject005=1 : Homoscedasticity      234
Name: Result_test, dtype: int64