<a href="https://colab.research.google.com/github/iam-fern/Generate_data/blob/main/ex_sampling_1000rep_n20_x4_norm_sas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

import statistics as stats
import scipy.stats as ss
from scipy.stats import f_oneway
from scipy import stats
import scipy.stats as stats
import time
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
df = pd.read_csv('https://github.com/iam-fern/Research/raw/main/sampling_1000rep_n20_x4_norm_sas.csv', index_col=['rep', 'index'])
df

                   x1        x2        x3  ...          Y      y_hat      e_hat
rep   index                                ...
0.0   0.0    0.849895 -0.009354 -1.078553  ...  12.471032  12.412881   0.058151
      1.0   -0.676925  0.274627 -0.311918  ...  -1.784818  -1.893203   0.108385
      2.0   -2.377971 -1.159588  1.343224  ...   9.498125 -18.671168  28.169293
      3.0   -0.402753  1.583468 -0.757062  ...   1.784095   1.624215   0.159880
      4.0    1.359371 -0.278202 -0.814965  ...  16.778133  17.517315  -0.739181
...               ...       ...       ...  ...        ...        ...        ...
999.0 15.0   0.007047  0.427579 -0.664201  ...   4.833847   4.762258   0.071589
      16.0   0.732119  0.484542  0.543849  ...  13.288874  13.211465   0.077409
      17.0   0.671912  0.907358  0.002601  ...  12.657754  12.483836   0.173918
      18.0  -0.971166  1.330098  0.376406  ...  -4.077158  -3.229910  -0.847248
      19.0   0.168349 -0.136004 -0.210551  ...   6.335079   6.291390   0.043689

[20000 rows x 7 columns]

In [3]:
# ลบข้อมูลที่มี missing values
table = df.dropna()
table

                   x1        x2        x3  ...          Y      y_hat      e_hat
rep   index                                ...
0.0   0.0    0.849895 -0.009354 -1.078553  ...  12.471032  12.412881   0.058151
      1.0   -0.676925  0.274627 -0.311918  ...  -1.784818  -1.893203   0.108385
      2.0   -2.377971 -1.159588  1.343224  ...   9.498125 -18.671168  28.169293
      3.0   -0.402753  1.583468 -0.757062  ...   1.784095   1.624215   0.159880
      4.0    1.359371 -0.278202 -0.814965  ...  16.778133  17.517315  -0.739181
...               ...       ...       ...  ...        ...        ...        ...
999.0 15.0   0.007047  0.427579 -0.664201  ...   4.833847   4.762258   0.071589
      16.0   0.732119  0.484542  0.543849  ...  13.288874  13.211465   0.077409
      17.0   0.671912  0.907358  0.002601  ...  12.657754  12.483836   0.173918
      18.0  -0.971166  1.330098  0.376406  ...  -4.077158  -3.229910  -0.847248
      19.0   0.168349 -0.136004 -0.210551  ...   6.335079   6.291390   0.043689

[20000 rows x 7 columns]

In [4]:
table.reset_index(inplace=True)
table

         rep  index        x1  ...          Y      y_hat      e_hat
0        0.0    0.0  0.849895  ...  12.471032  12.412881   0.058151
1        0.0    1.0 -0.676925  ...  -1.784818  -1.893203   0.108385
2        0.0    2.0 -2.377971  ...   9.498125 -18.671168  28.169293
3        0.0    3.0 -0.402753  ...   1.784095   1.624215   0.159880
4        0.0    4.0  1.359371  ...  16.778133  17.517315  -0.739181
...      ...    ...       ...  ...        ...        ...        ...
19995  999.0   15.0  0.007047  ...   4.833847   4.762258   0.071589
19996  999.0   16.0  0.732119  ...  13.288874  13.211465   0.077409
19997  999.0   17.0  0.671912  ...  12.657754  12.483836   0.173918
19998  999.0   18.0 -0.971166  ...  -4.077158  -3.229910  -0.847248
19999  999.0   19.0  0.168349  ...   6.335079   6.291390   0.043689

[20000 rows x 9 columns]

In [5]:
table.set_index(['rep', 'index'], inplace=True)

In [6]:
table

                   x1        x2        x3  ...          Y      y_hat      e_hat
rep   index                                ...
0.0   0.0    0.849895 -0.009354 -1.078553  ...  12.471032  12.412881   0.058151
      1.0   -0.676925  0.274627 -0.311918  ...  -1.784818  -1.893203   0.108385
      2.0   -2.377971 -1.159588  1.343224  ...   9.498125 -18.671168  28.169293
      3.0   -0.402753  1.583468 -0.757062  ...   1.784095   1.624215   0.159880
      4.0    1.359371 -0.278202 -0.814965  ...  16.778133  17.517315  -0.739181
...               ...       ...       ...  ...        ...        ...        ...
999.0 15.0   0.007047  0.427579 -0.664201  ...   4.833847   4.762258   0.071589
      16.0   0.732119  0.484542  0.543849  ...  13.288874  13.211465   0.077409
      17.0   0.671912  0.907358  0.002601  ...  12.657754  12.483836   0.173918
      18.0  -0.971166  1.330098  0.376406  ...  -4.077158  -3.229910  -0.847248
      19.0   0.168349 -0.136004 -0.210551  ...   6.335079   6.291390   0.043689

[20000 rows x 7 columns]

In [7]:
def get_result(run_replicate, percent_data):
    new_table = table.loc[run_replicate]

    # เรียง data จากน้อยไปมากตาม x1
    new_table_sort = new_table.sort_values('x1')

    new_table_sort.reset_index(inplace=True)

    #new_table_sort.drop(['index'], axis=1, inplace=True)


    # แบ่งข้อมูลกลุ่มที่ 1
    table1 = new_table_sort.iloc[:int(percent_data*new_table_sort.shape[0]) , :]
    # define respones variable
    y = table1['Y']
    # define predictor variable
    x = table1[['x1', 'x2', 'x3']]
    # add constant to predictor variable
    x = sm.add_constant(x)
    # fit linear regression model
    model1 = sm.OLS(y, x).fit()

    # หาค่า df กลุ่ม 1
    DF1 = model1.df_resid
    # หาค่า SSE1 : Residual sum of squares
    SSE1 = model1.ssr
    # หาค่า MSE1
    MSE1 = model1.mse_resid


    # แบ่งข้อมูลกลุ่มที่ 2
    table2 = new_table_sort.iloc[int((1-percent_data)*new_table_sort.shape[0]): , :]

    y = table2['Y']
    x = table2[['x1', 'x2', 'x3']]
    x = sm.add_constant(x)
    model2 = sm.OLS(y, x).fit()
    #print(model.summary())

    # หาค่า df กลุ่ม 2
    DF2 = model2.df_resid
    # หาค่า SSE2 : : Residual sum of squares
    SSE2 = model2.ssr
    # หาค่า MSE2
    MSE2 = model2.mse_resid

    df2 = DF2+1
    df1 = DF1+1

    # ค่าสถิติทดสอบ
    GQ_test = (SSE2/df2) / (SSE1/df1)

    # คำนวณค่า p-value
    # sf(x, dfn, dfd, loc=0, scale=1) : Survival function (also defined as 1 - cdf, but sf is sometimes more accurate)
    two_tailed = 2.0*(1.0-(ss.f.cdf(GQ_test, df2, df1)))

    # pdf(x, dfn, dfd, loc=0, scale=1) : Probability density function
    p_greater = ss.f.cdf(GQ_test, df2, df1)
    
    return df2, df1, SSE2, SSE1, MSE2, MSE1, GQ_test, two_tailed, p_greater
    

    # เปรียบเทียบค่า p-value กับค่า alpha
    # Homoscedasticity : 0
    # Heteroscedasticity : 1
    #if p_value < alpha:
        #result_test='Reject005=0 : Heteroscedasticity '
        #result_test01=1
    #else:
        #result_test='Reject005=1 : Homoscedasticity '
        #result_test01=0
    
    #return df1, df2, SSE1, SSE2, MSE1, MSE2, GQ_test, result_test, p_value, result_test01


# สร้าง list ของ replicates
list_replicate=list({i[0] for i in table.index})
list_replicate.sort()

# สร้าง list เพื่อเก็บค่า ทุกรอบที่ run
list_df1=[]
list_df2=[]
list_SSE1=[]
list_SSE2=[]
list_MSE1=[]
list_MSE2=[]
list_GQ_test=[]
#list_result_test=[]
list_two_tailed=[]
list_p_greater=[]
#list_result_test01=[]


# กำหนด % การแบ่งข้อมูล
percent_data=0.4

# ใช้ for loop สำหรับการ run ทุก replicates
for run_replicate in list_replicate:
    #DF1, DF2, SSE1, SSE2, M_SSE1, M_SSE2, GQ_test, result_test=get_result(run_replicate, percent_data)
    df1, df2, SSE1, SSE2, MSE1, MSE2, GQ_test, two_tailed, p_greater=get_result(run_replicate, percent_data)
    list_df1.append(df1)
    list_SSE1.append(SSE1)
    list_df2.append(df2)
    list_SSE2.append(SSE2)
    list_MSE1.append(MSE1)
    list_MSE2.append(MSE2)
    list_GQ_test.append(GQ_test)
    #list_result_test.append(result_test)
    list_two_tailed.append(two_tailed)
    list_p_greater.append(p_greater)
    #list_result_test01.append(result_test01)

In [8]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
result=pd.DataFrame({"Replicate":list_replicate, "df1":list_df1, "df2":list_df2, "SSE1":list_SSE1,
                     "SSE2":list_SSE2, "MSE1":list_MSE1, "MSE2":list_MSE2,
                     "GQ_test":list_GQ_test, "two_tailed":list_two_tailed, "greater":list_p_greater})
result.set_index(['Replicate'], inplace=True)
result=result[(result["two_tailed"]<=1) & (result["greater"]<=1)]
result["Result_test"]=result["two_tailed"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                  if p_value < alpha else 'Reject005=1 : Homoscedasticity')
#two_tailed_new_show=two_tailed_new.drop(columns="greater")

result.astype(str)

           df1  df2                SSE1                SSE2                MSE1                 MSE2             GQ_test              two_tailed             greater                       Result_test
Replicate
1.0        5.0  5.0  1.3043737405495828  0.7744912451948027  0.3260934351373957  0.19362281129870068  1.6841684765868492       0.581203290511028   0.709398354744486    Reject005=1 : Homoscedasticity
2.0        5.0  5.0  10.366509607549835   8.007109874435791  2.5916274018874588    2.001777468608948  1.2946630894434048      0.7837933396953618  0.6081033301523191    Reject005=1 : Homoscedasticity
3.0        5.0  5.0   568.9373810815723  193.08378332798327  142.23434527039308    48.27094583199582  2.9465829355287823      0.2606825887615254  0.8696587056192373    Reject005=1 : Homoscedasticity
4.0        5.0  5.0    6.56185134059353   2.750488591986696  1.6404628351483825    0.687622147996674  2.3857038926505276      0.3618849351713076  0.8190575324143462    Reject005=1 : Homoscedasticity
7.0        5.0  5.0  408.57869601275866  3.6978663011272057  102.14467400318966   0.9244665752818014  110.49039168566297    8.19877197772989e-05  0.9999590061401114  Reject005=0 : Heteroscedasticity
...        ...  ...                 ...                 ...                 ...                  ...                 ...                     ...                 ...                               ...
991.0      5.0  5.0   9.923207810387122  2.1679908976553244  2.4808019525967806   0.5419977244138311   4.577144590929344     0.12051174358511507  0.9397441282074425    Reject005=1 : Homoscedasticity
992.0      5.0  5.0   4.666263267043947  0.9109487386355921  1.1665658167609867  0.22773718465889803    5.12242134945268      0.0973102620273254  0.9513448689863373    Reject005=1 : Homoscedasticity
993.0      5.0  5.0  100.98652515633913  48.036277955328295   25.24663128908478   12.009069488832074   2.102297044126781      0.4341409554392124  0.7829295222803938    Reject005=1 : Homoscedasticity
995.0      5.0  5.0   48.18188640317625  0.7403638540685977  12.045471600794063  0.18509096351714943    65.0786584709631  0.00030116003215763243  0.9998494199839212  Reject005=0 : Heteroscedasticity
997.0      5.0  5.0   59.05542705425158   17.75984413634149  14.763856763562895    4.439961034085372  3.3252221472714423       0.213298236044821  0.8933508819775895    Reject005=1 : Homoscedasticity

[506 rows x 10 columns]

In [9]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
result=pd.DataFrame({"Replicate":list_replicate, "df1":list_df1, "df2":list_df2, "SSE1":list_SSE1,
                     "SSE2":list_SSE2, "MSE1":list_MSE1, "MSE2":list_MSE2,
                     "GQ_test":list_GQ_test, "two_tailed":list_two_tailed, "greater":list_p_greater})
result.set_index(['Replicate'], inplace=True)

result['two_tailed_new']=result[["two_tailed","greater"]].apply(lambda value: value[0] if value[0]<0.5 else 2*value[1], axis=1)
result["Result_test"]=result["two_tailed"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                  if p_value < alpha else 'Reject005=1 : Homoscedasticity')
#two_tailed_new_show=two_tailed_new.drop(columns="greater")
result_show=result.drop(columns=["two_tailed", "greater"])
result_show.astype(str)

           df1  df2                SSE1                SSE2                  MSE1                 MSE2                GQ_test          two_tailed_new                       Result_test
Replicate
0.0        5.0  5.0  0.1374393234383893  27.483975307491917  0.034359830859597325    6.870993826872979     0.0050007075723476  1.8874362380443936e-05    Reject005=1 : Homoscedasticity
1.0        5.0  5.0  1.3043737405495828  0.7744912451948027    0.3260934351373957  0.19362281129870068     1.6841684765868492       1.418796709488972    Reject005=1 : Homoscedasticity
2.0        5.0  5.0  10.366509607549835   8.007109874435791    2.5916274018874588    2.001777468608948     1.2946630894434048      1.2162066603046382    Reject005=1 : Homoscedasticity
3.0        5.0  5.0   568.9373810815723  193.08378332798327    142.23434527039308    48.27094583199582     2.9465829355287823      0.2606825887615254    Reject005=1 : Homoscedasticity
4.0        5.0  5.0    6.56185134059353   2.750488591986696    1.6404628351483825    0.687622147996674     2.3857038926505276      0.3618849351713076    Reject005=1 : Homoscedasticity
...        ...  ...                 ...                 ...                   ...                  ...                    ...                     ...                               ...
995.0      5.0  5.0   48.18188640317625  0.7403638540685977    12.045471600794063  0.18509096351714943       65.0786584709631  0.00030116003215763243  Reject005=0 : Heteroscedasticity
996.0      5.0  5.0  7.3171009040949775   87.03725899153285    1.8292752260237444   21.759314747883213    0.08406860451346243    0.016706998577622017    Reject005=1 : Homoscedasticity
997.0      5.0  5.0   59.05542705425158   17.75984413634149    14.763856763562895    4.439961034085372     3.3252221472714423       0.213298236044821    Reject005=1 : Homoscedasticity
998.0      5.0  5.0  251.68185669924353  2715.3964809765575     62.92046417481088    678.8491202441394    0.09268696430243932    0.020733828706721937    Reject005=1 : Homoscedasticity
999.0      5.0  5.0  0.9568498886006414   707.0850323254598   0.23921247215016034   176.77125808136495  0.0013532317116850224   7.283864650874816e-07    Reject005=1 : Homoscedasticity

[1000 rows x 9 columns]

In [10]:
result_show['Result_test'].value_counts()

Reject005=1 : Homoscedasticity      710
Reject005=0 : Heteroscedasticity    290
Name: Result_test, dtype: int64