<a href="https://colab.research.google.com/github/iam-fern/Generate_data/blob/main/ex_sampling_c_1000rep_n30_x2_norm_sas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

import statistics as stats
import scipy.stats as ss
import scipy.stats as st
from scipy.stats import f_oneway
from scipy import stats
import scipy.stats as stats
import time
import statsmodels.api as sm

from statsmodels.formula.api import ols

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
df = pd.read_csv('https://github.com/iam-fern/Research/raw/main/sampling_1000rep_n30_x2_norm_sas.csv', index_col=['rep', 'index'])
df

                   x1        x2        x3  ...          Y      y_hat     e_hat
rep   index                                ...
0.0   0.0    0.493867 -0.227286 -1.247506  ...   8.520469   8.430459  0.090010
      1.0   -0.532480 -1.473404 -0.291457  ...  -1.860661  -2.108621  0.247960
      2.0    0.785565  1.547871  0.085528  ...  14.299159  14.486428 -0.187269
      3.0    0.916724  0.856775 -1.202542  ...  13.266400  13.793152 -0.526752
      4.0    0.542729 -3.087517 -0.016574  ...   6.876250   7.283326 -0.407076
...               ...       ...       ...  ...        ...        ...       ...
999.0 25.0  -1.699804  1.937634  0.343864  ...  -9.733762  -9.685590 -0.048172
      26.0   0.267239 -0.028352  2.205519  ...   9.757088   9.870009 -0.112922
      27.0   1.217884 -0.169147 -0.169056  ...  20.869329  16.815501  4.053828
      28.0   1.007549  0.469520  0.024998  ...  13.672901  15.555207 -1.882307
      29.0   1.699051  0.310231 -1.052602  ...  18.904833  21.209076 -2.304243

[30000 rows x 7 columns]

In [3]:
# ลบข้อมูลที่มี missing values
table = df.dropna()
table

                   x1        x2        x3  ...          Y      y_hat     e_hat
rep   index                                ...
0.0   0.0    0.493867 -0.227286 -1.247506  ...   8.520469   8.430459  0.090010
      1.0   -0.532480 -1.473404 -0.291457  ...  -1.860661  -2.108621  0.247960
      2.0    0.785565  1.547871  0.085528  ...  14.299159  14.486428 -0.187269
      3.0    0.916724  0.856775 -1.202542  ...  13.266400  13.793152 -0.526752
      4.0    0.542729 -3.087517 -0.016574  ...   6.876250   7.283326 -0.407076
...               ...       ...       ...  ...        ...        ...       ...
999.0 25.0  -1.699804  1.937634  0.343864  ...  -9.733762  -9.685590 -0.048172
      26.0   0.267239 -0.028352  2.205519  ...   9.757088   9.870009 -0.112922
      27.0   1.217884 -0.169147 -0.169056  ...  20.869329  16.815501  4.053828
      28.0   1.007549  0.469520  0.024998  ...  13.672901  15.555207 -1.882307
      29.0   1.699051  0.310231 -1.052602  ...  18.904833  21.209076 -2.304243

[30000 rows x 7 columns]

In [4]:
table.reset_index(inplace=True)
table

         rep  index        x1  ...          Y      y_hat     e_hat
0        0.0    0.0  0.493867  ...   8.520469   8.430459  0.090010
1        0.0    1.0 -0.532480  ...  -1.860661  -2.108621  0.247960
2        0.0    2.0  0.785565  ...  14.299159  14.486428 -0.187269
3        0.0    3.0  0.916724  ...  13.266400  13.793152 -0.526752
4        0.0    4.0  0.542729  ...   6.876250   7.283326 -0.407076
...      ...    ...       ...  ...        ...        ...       ...
29995  999.0   25.0 -1.699804  ...  -9.733762  -9.685590 -0.048172
29996  999.0   26.0  0.267239  ...   9.757088   9.870009 -0.112922
29997  999.0   27.0  1.217884  ...  20.869329  16.815501  4.053828
29998  999.0   28.0  1.007549  ...  13.672901  15.555207 -1.882307
29999  999.0   29.0  1.699051  ...  18.904833  21.209076 -2.304243

[30000 rows x 9 columns]

In [5]:
table.set_index(['rep', 'index'], inplace=True)

In [6]:
table

                   x1        x2        x3  ...          Y      y_hat     e_hat
rep   index                                ...
0.0   0.0    0.493867 -0.227286 -1.247506  ...   8.520469   8.430459  0.090010
      1.0   -0.532480 -1.473404 -0.291457  ...  -1.860661  -2.108621  0.247960
      2.0    0.785565  1.547871  0.085528  ...  14.299159  14.486428 -0.187269
      3.0    0.916724  0.856775 -1.202542  ...  13.266400  13.793152 -0.526752
      4.0    0.542729 -3.087517 -0.016574  ...   6.876250   7.283326 -0.407076
...               ...       ...       ...  ...        ...        ...       ...
999.0 25.0  -1.699804  1.937634  0.343864  ...  -9.733762  -9.685590 -0.048172
      26.0   0.267239 -0.028352  2.205519  ...   9.757088   9.870009 -0.112922
      27.0   1.217884 -0.169147 -0.169056  ...  20.869329  16.815501  4.053828
      28.0   1.007549  0.469520  0.024998  ...  13.672901  15.555207 -1.882307
      29.0   1.699051  0.310231 -1.052602  ...  18.904833  21.209076 -2.304243

[30000 rows x 7 columns]

In [7]:
def get_result(run_replicate):
    new_table = table.loc[run_replicate]

    # show index
    new_table.reset_index(inplace=True)

    new_table.drop(['index'], axis=1, inplace=True)


    # แบ่งข้อมูลออกเป็น 2 กลุ่มด้วย k-mean

    #Set number of clusters
    x = new_table[["x1", "x2", "x3"]]
    k_means = KMeans(n_clusters=2)

    #Run the clustering algorithm
    model = k_means.fit(x)
    model

    #Generate cluster predictions and store in y_kmeans
    y_kmeans = k_means.predict(x)
    y_kmeans

    # kmean_clusters.astype(float)
    kmean_clusters = pd.DataFrame({"clusters" : y_kmeans})

    # เชื่อมข้อมูลทั้ง 2 DataFrame เข้าด้วยกันด้วยคำสั่ง pd.concat
    data_clusters = pd.concat([new_table, kmean_clusters], axis=1)

    data_sort_clusters = data_clusters.sort_values('clusters')

    # print(data_clusters.groupby('clusters').groups)

    data_sort_clusters.reset_index(inplace=True)

    # กลุ่มที่ 1
    data_cluster1 = data_sort_clusters[data_sort_clusters.clusters == 1]

    y = data_cluster1[['Y']]
    x = data_cluster1[['x1', 'x2', 'x3']]
    x = sm.add_constant(x)
    model1 = sm.OLS(y, x).fit()

    DF1 = model1.df_resid

    SSR1 = model1.ssr

    MSE1 = model1.mse_resid

    # กลุ่มที่ 2
    data_cluster0 = data_sort_clusters[data_sort_clusters.clusters == 0]

    y = data_cluster0[['Y']]
    x = data_cluster0[['x1', 'x2', 'x3']]
    x = sm.add_constant(x)
    model0 = sm.OLS(y, x).fit()

    DF0 = model0.df_resid

    SSR0 = model0.ssr

    MSE0 = model0.mse_resid

    df1 = DF1+1
    df0 = DF0+1

    # คำนวณค่าสถิติ
    GQ_test_clusters = (SSR1/df1) / (SSR0/df0)


    # คำนวณค่า p-value
    # sf(x, dfn, dfd, loc=0, scale=1) : Survival function (also defined as 1 - cdf, but sf is sometimes more accurate)
    two_tailed = 2.0*(1.0-(ss.f.cdf(GQ_test_clusters, df1, df0)))

    # pdf(x, dfn, dfd, loc=0, scale=1) : Probability density function
    p_greater = ss.f.cdf(GQ_test_clusters, df1, df0)
    
    return df0, df1, SSR0, SSR1, MSE0, MSE1, GQ_test_clusters, two_tailed, p_greater

# สร้าง list ของ replicates
list_replicate=list({i[0] for i in table.index})
list_replicate.sort()

# สร้าง list เพื่อเก็บค่า ทุกรอบที่ run
list_df0=[]
list_df1=[]
list_SSR0=[]
list_SSR1=[]
list_MSE0=[]
list_MSE1=[]
list_GQ_test_clusters=[]
list_result_test=[]
list_two_tailed=[]
list_p_greater=[]
list_result_test01=[]

# ใช้ for loop สำหรับการ run ทุก replicates
for run_replicate in list_replicate:
    df0, df1, SSR0, SSR1, MSE0, MSE1, GQ_test_clusters, two_tailed, p_greater=get_result(run_replicate)

    list_df0.append(df0)
    list_df1.append(df1)
    list_SSR0.append(SSR0)
    list_SSR1.append(SSR1)
    list_MSE0.append(MSE0)
    list_MSE1.append(MSE1)
    list_GQ_test_clusters.append(GQ_test_clusters)
    list_two_tailed.append(two_tailed)
    list_p_greater.append(p_greater)

/usr/local/lib/python3.7/dist-packages/statsmodels/regression/linear_model.py:1665: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid
/usr/local/lib/python3.7/dist-packages/statsmodels/regression/linear_model.py:1665: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid
/usr/local/lib/python3.7/dist-packages/statsmodels/regression/linear_model.py:1665: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid
/usr/local/lib/python3.7/dist-packages/statsmodels/regression/linear_model.py:1665: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid

In [8]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
two_tailed_new=pd.DataFrame({"Replicate":list_replicate, "df0":list_df0, "df1":list_df1, "SSR0":list_SSR0,
                     "SSR1":list_SSR1, "MSE0":list_MSE0, "MSE1":list_MSE1, 
                     "GQ_test_clusters":list_GQ_test_clusters, "two_tailed":list_two_tailed, "greater":list_p_greater})
two_tailed_new.set_index(['Replicate'], inplace=True)
two_tailed_new=two_tailed_new[(two_tailed_new["two_tailed"]<=1) & (two_tailed_new["greater"]<=1)]
two_tailed_new["Result_test"]=two_tailed_new["two_tailed"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                  if p_value < alpha else 'Reject005=1 : Homoscedasticity')
#two_tailed_new_show=two_tailed_new.drop(columns="greater")
two_tailed_new.astype(str)

            df0   df1                  SSR0                SSR1                  MSE0                MSE1    GQ_test_clusters              two_tailed             greater                       Result_test
Replicate
1.0        11.0  13.0     2.843944877412546  10.103208334534516   0.28439448774125464  0.8419340278778763   3.005989552982417     0.07573480196367166  0.9621325990181642    Reject005=1 : Homoscedasticity
3.0        12.0  12.0     4.457996530352329    49.6275850853294   0.40527241185021173   4.511598644120855  11.132261935925548  0.00020111671548161958  0.9998994416422592  Reject005=0 : Heteroscedasticity
4.0         8.0  16.0    6.5245836416760525   18.12536424226196    0.9320833773822932  1.2083576161507972  1.3890054321999517      0.6557027875770585  0.6721486062114708    Reject005=1 : Homoscedasticity
6.0        21.0   3.0    48.516393071442046  11.748106678517319    2.4258196535721024   5.874053339258659  1.6950301030937072      0.3972393765765978  0.8013803117117011    Reject005=1 : Homoscedasticity
8.0         3.0  21.0  0.013405540545933185  200.44487352489418  0.006702770272966592   10.02224367624471   2136.055747547956  2.8969290713165563e-05  0.9999855153546434  Reject005=0 : Heteroscedasticity
...         ...   ...                   ...                 ...                   ...                 ...                 ...                     ...                 ...                               ...
984.0       8.0  16.0    13.881312615767287   51.50605362502272    1.9830446593953268  3.4337369083348483  1.8552299429709131     0.37875349346921805   0.810623253265391    Reject005=1 : Homoscedasticity
990.0      13.0  11.0    2.6276080133536395   9.699259720921724    0.2189673344461366  0.9699259720921724   4.362432078950777    0.014187578966055492  0.9929062105169723  Reject005=0 : Heteroscedasticity
991.0      12.0  12.0     3.094929071708238  27.061550249015024   0.28135718833711254  2.4601409317286387   8.743835358423407   0.0006826525560816865  0.9996586737219592  Reject005=0 : Heteroscedasticity
993.0       9.0  15.0     4.141303542199746   7.710656763170409    0.5176629427749683   0.550761197369315  1.1171347404891823      0.8960123560191806  0.5519938219904097    Reject005=1 : Homoscedasticity
995.0       8.0  16.0    3.7223793543017893   38.09201859671849    0.5317684791859699   2.539467906447899   5.116622322856109    0.024843633436602675  0.9875781832816987  Reject005=0 : Heteroscedasticity

[533 rows x 10 columns]

In [9]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
two_tailed_new=pd.DataFrame({"Replicate":list_replicate, "df0":list_df0, "df1":list_df1, "SSR0":list_SSR0,
                     "SSR1":list_SSR1, "MSE0":list_MSE0, "MSE1":list_MSE1,
                     "GQ_test_clusters":list_GQ_test_clusters, "two_tailed":list_two_tailed, "greater":list_p_greater})
two_tailed_new.set_index(['Replicate'], inplace=True)

two_tailed_new["two_tailed_new"]=two_tailed_new[["two_tailed","greater"]].apply(lambda value: value[0] if value[0]<0.5 else 2*value[1], axis=1)
two_tailed_new["Result_test"]=two_tailed_new["two_tailed_new"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                      if p_value < alpha else 'Reject005=1 : Homoscedasticity')


two_tailed_new_show=two_tailed_new.drop(columns=["two_tailed", "greater"])
two_tailed_new_show.astype(str)

            df0   df1                SSR0                 SSR1                 MSE0                  MSE1       GQ_test_clusters          two_tailed_new                       Result_test
Replicate
0.0        10.0  14.0   31.52825141647223    8.004045918387181    3.503139046274692     0.615695839875937    0.18133500587995985    0.004239059073380686  Reject005=0 : Heteroscedasticity
1.0        11.0  13.0   2.843944877412546   10.103208334534516  0.28439448774125464    0.8419340278778763      3.005989552982417     0.07573480196367166    Reject005=1 : Homoscedasticity
2.0        10.0  14.0  42.888476181169644  0.21666761427374268    4.765386242352182  0.016666739559518667  0.0036084886991636935   5.257046193862517e-14  Reject005=0 : Heteroscedasticity
3.0        12.0  12.0   4.457996530352329     49.6275850853294  0.40527241185021173     4.511598644120855     11.132261935925548  0.00020111671548161958  Reject005=0 : Heteroscedasticity
4.0         8.0  16.0  6.5245836416760525    18.12536424226196   0.9320833773822932    1.2083576161507972     1.3890054321999517      1.3442972124229415    Reject005=1 : Homoscedasticity
...         ...   ...                 ...                  ...                  ...                   ...                    ...                     ...                               ...
995.0       8.0  16.0  3.7223793543017893    38.09201859671849   0.5317684791859699     2.539467906447899      5.116622322856109    0.024843633436602675  Reject005=0 : Heteroscedasticity
996.0      10.0  14.0   16.63037579001324   17.223802726415876   1.8478195322236932    1.3249079020319905     0.7397737963649709      0.5890514540936436    Reject005=1 : Homoscedasticity
997.0      12.0  12.0   15.57405422658617    9.876473615619727   1.4158231115078337    0.8978612377836115     0.6341620153575545      0.4416626579688411    Reject005=1 : Homoscedasticity
998.0      16.0   8.0   60.18537228117758   16.183845605309628    4.012358152078505    2.3119779436156613     0.5377999667328128     0.37696019879511644    Reject005=1 : Homoscedasticity
999.0      15.0   9.0   50.33488070034307    7.919568964311638   3.5953486214530765    0.9899461205389547     0.2622293213679177     0.04817393161111628  Reject005=0 : Heteroscedasticity

[1000 rows x 9 columns]

In [10]:
two_tailed_new_show['Result_test'].value_counts()

Reject005=1 : Homoscedasticity      536
Reject005=0 : Heteroscedasticity    464
Name: Result_test, dtype: int64