<a href="https://colab.research.google.com/github/iam-fern/Generate_data/blob/main/ex_sampling_c_1000rep_n50_x2_norm_sas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

import statistics as stats
import scipy.stats as ss
import scipy.stats as st
from scipy.stats import f_oneway
from scipy import stats
import scipy.stats as stats
import time
import statsmodels.api as sm

from statsmodels.formula.api import ols

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
df = pd.read_csv('https://github.com/iam-fern/Research/raw/main/sampling_1000rep_n50_x2_norm_sas.csv', index_col=['rep', 'index'])
df

                   x1        x2        x3  ...          Y      y_hat     e_hat
rep   index                                ...
0.0   0.0    1.604843 -0.488783  0.975761  ...  20.609794  21.582432 -0.972639
      1.0   -1.149485  0.343755 -0.442063  ...  -5.032654  -6.624869  1.592215
      2.0   -1.233989  0.073204  0.900708  ...  -8.140479  -6.409230 -1.731249
      3.0   -0.709294 -0.533403  1.795343  ...  -0.857321  -0.861359  0.004039
      4.0   -1.700392  0.893505  0.321056  ...  -3.862198 -10.847563  6.985365
...               ...       ...       ...  ...        ...        ...       ...
999.0 45.0   0.153887 -0.434666  1.406145  ...   7.463847   7.508995 -0.045148
      46.0   0.971936  2.406012 -1.434739  ...  15.643832  15.718927 -0.075095
      47.0   0.325140  0.864184 -0.251488  ...   9.060957   8.872907  0.188049
      48.0  -0.416267 -0.344077 -0.522636  ...  -0.185893  -0.033530 -0.152363
      49.0  -0.717375  0.918834  0.366525  ...  -0.208553  -0.916887  0.708334

[50000 rows x 7 columns]

In [3]:
# ลบข้อมูลที่มี missing values
table = df.dropna()
table

                   x1        x2        x3  ...          Y      y_hat     e_hat
rep   index                                ...
0.0   0.0    1.604843 -0.488783  0.975761  ...  20.609794  21.582432 -0.972639
      1.0   -1.149485  0.343755 -0.442063  ...  -5.032654  -6.624869  1.592215
      2.0   -1.233989  0.073204  0.900708  ...  -8.140479  -6.409230 -1.731249
      3.0   -0.709294 -0.533403  1.795343  ...  -0.857321  -0.861359  0.004039
      4.0   -1.700392  0.893505  0.321056  ...  -3.862198 -10.847563  6.985365
...               ...       ...       ...  ...        ...        ...       ...
999.0 45.0   0.153887 -0.434666  1.406145  ...   7.463847   7.508995 -0.045148
      46.0   0.971936  2.406012 -1.434739  ...  15.643832  15.718927 -0.075095
      47.0   0.325140  0.864184 -0.251488  ...   9.060957   8.872907  0.188049
      48.0  -0.416267 -0.344077 -0.522636  ...  -0.185893  -0.033530 -0.152363
      49.0  -0.717375  0.918834  0.366525  ...  -0.208553  -0.916887  0.708334

[50000 rows x 7 columns]

In [4]:
table.reset_index(inplace=True)
table

         rep  index        x1  ...          Y      y_hat     e_hat
0        0.0    0.0  1.604843  ...  20.609794  21.582432 -0.972639
1        0.0    1.0 -1.149485  ...  -5.032654  -6.624869  1.592215
2        0.0    2.0 -1.233989  ...  -8.140479  -6.409230 -1.731249
3        0.0    3.0 -0.709294  ...  -0.857321  -0.861359  0.004039
4        0.0    4.0 -1.700392  ...  -3.862198 -10.847563  6.985365
...      ...    ...       ...  ...        ...        ...       ...
49995  999.0   45.0  0.153887  ...   7.463847   7.508995 -0.045148
49996  999.0   46.0  0.971936  ...  15.643832  15.718927 -0.075095
49997  999.0   47.0  0.325140  ...   9.060957   8.872907  0.188049
49998  999.0   48.0 -0.416267  ...  -0.185893  -0.033530 -0.152363
49999  999.0   49.0 -0.717375  ...  -0.208553  -0.916887  0.708334

[50000 rows x 9 columns]

In [5]:
table.set_index(['rep', 'index'], inplace=True)

In [6]:
table

                   x1        x2        x3  ...          Y      y_hat     e_hat
rep   index                                ...
0.0   0.0    1.604843 -0.488783  0.975761  ...  20.609794  21.582432 -0.972639
      1.0   -1.149485  0.343755 -0.442063  ...  -5.032654  -6.624869  1.592215
      2.0   -1.233989  0.073204  0.900708  ...  -8.140479  -6.409230 -1.731249
      3.0   -0.709294 -0.533403  1.795343  ...  -0.857321  -0.861359  0.004039
      4.0   -1.700392  0.893505  0.321056  ...  -3.862198 -10.847563  6.985365
...               ...       ...       ...  ...        ...        ...       ...
999.0 45.0   0.153887 -0.434666  1.406145  ...   7.463847   7.508995 -0.045148
      46.0   0.971936  2.406012 -1.434739  ...  15.643832  15.718927 -0.075095
      47.0   0.325140  0.864184 -0.251488  ...   9.060957   8.872907  0.188049
      48.0  -0.416267 -0.344077 -0.522636  ...  -0.185893  -0.033530 -0.152363
      49.0  -0.717375  0.918834  0.366525  ...  -0.208553  -0.916887  0.708334

[50000 rows x 7 columns]

In [7]:
def get_result(run_replicate):
    new_table = table.loc[run_replicate]

    # show index
    new_table.reset_index(inplace=True)

    new_table.drop(['index'], axis=1, inplace=True)


    # แบ่งข้อมูลออกเป็น 2 กลุ่มด้วย k-mean

    #Set number of clusters
    x = new_table[["x1", "x2", "x3"]]
    k_means = KMeans(n_clusters=2)

    #Run the clustering algorithm
    model = k_means.fit(x)
    model

    #Generate cluster predictions and store in y_kmeans
    y_kmeans = k_means.predict(x)
    y_kmeans

    # kmean_clusters.astype(float)
    kmean_clusters = pd.DataFrame({"clusters" : y_kmeans})

    # เชื่อมข้อมูลทั้ง 2 DataFrame เข้าด้วยกันด้วยคำสั่ง pd.concat
    data_clusters = pd.concat([new_table, kmean_clusters], axis=1)

    data_sort_clusters = data_clusters.sort_values('clusters')

    # print(data_clusters.groupby('clusters').groups)

    data_sort_clusters.reset_index(inplace=True)

    # กลุ่มที่ 1
    data_cluster1 = data_sort_clusters[data_sort_clusters.clusters == 1]

    y = data_cluster1[['Y']]
    x = data_cluster1[['x1', 'x2', 'x3']]
    x = sm.add_constant(x)
    model1 = sm.OLS(y, x).fit()

    DF1 = model1.df_resid

    SSR1 = model1.ssr

    MSE1 = model1.mse_resid

    # กลุ่มที่ 2
    data_cluster0 = data_sort_clusters[data_sort_clusters.clusters == 0]

    y = data_cluster0[['Y']]
    x = data_cluster0[['x1', 'x2', 'x3']]
    x = sm.add_constant(x)
    model0 = sm.OLS(y, x).fit()

    DF0 = model0.df_resid

    SSR0 = model0.ssr

    MSE0 = model0.mse_resid

    df1 = DF1+1
    df0 = DF0+1

    # คำนวณค่าสถิติ
    GQ_test_clusters = (SSR1/df1) / (SSR0/df0)


    # คำนวณค่า p-value
    # sf(x, dfn, dfd, loc=0, scale=1) : Survival function (also defined as 1 - cdf, but sf is sometimes more accurate)
    two_tailed = 2.0*(1.0-(ss.f.cdf(GQ_test_clusters, df1, df0)))

    # pdf(x, dfn, dfd, loc=0, scale=1) : Probability density function
    p_greater = ss.f.cdf(GQ_test_clusters, df1, df0)
    
    return df0, df1, SSR0, SSR1, MSE0, MSE1, GQ_test_clusters, two_tailed, p_greater

# สร้าง list ของ replicates
list_replicate=list({i[0] for i in table.index})
list_replicate.sort()

# สร้าง list เพื่อเก็บค่า ทุกรอบที่ run
list_df0=[]
list_df1=[]
list_SSR0=[]
list_SSR1=[]
list_MSE0=[]
list_MSE1=[]
list_GQ_test_clusters=[]
list_result_test=[]
list_two_tailed=[]
list_p_greater=[]
list_result_test01=[]

# ใช้ for loop สำหรับการ run ทุก replicates
for run_replicate in list_replicate:
    df0, df1, SSR0, SSR1, MSE0, MSE1, GQ_test_clusters, two_tailed, p_greater=get_result(run_replicate)

    list_df0.append(df0)
    list_df1.append(df1)
    list_SSR0.append(SSR0)
    list_SSR1.append(SSR1)
    list_MSE0.append(MSE0)
    list_MSE1.append(MSE1)
    list_GQ_test_clusters.append(GQ_test_clusters)
    list_two_tailed.append(two_tailed)
    list_p_greater.append(p_greater)

In [8]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
two_tailed_new=pd.DataFrame({"Replicate":list_replicate, "df0":list_df0, "df1":list_df1, "SSR0":list_SSR0,
                     "SSR1":list_SSR1, "MSE0":list_MSE0, "MSE1":list_MSE1, 
                     "GQ_test_clusters":list_GQ_test_clusters, "two_tailed":list_two_tailed, "greater":list_p_greater})
two_tailed_new.set_index(['Replicate'], inplace=True)
two_tailed_new=two_tailed_new[(two_tailed_new["two_tailed"]<=1) & (two_tailed_new["greater"]<=1)]
two_tailed_new["Result_test"]=two_tailed_new["two_tailed"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                  if p_value < alpha else 'Reject005=1 : Homoscedasticity')
#two_tailed_new_show=two_tailed_new.drop(columns="greater")
two_tailed_new.astype(str)

            df0   df1                SSR0                SSR1                MSE0                MSE1    GQ_test_clusters              two_tailed             greater                       Result_test
Replicate
0.0        13.0  31.0  14.510139012294935   67.26230121007926  1.2091782510245779  2.2420767070026417  1.9439353028454083     0.20355166206881714  0.8982241689655914    Reject005=1 : Homoscedasticity
1.0        28.0  16.0  39.808734119667854  28.953247694577996  1.4743975599876984  1.9302165129718665  1.2727906221081877      0.5593795519012352  0.7203102240493824    Reject005=1 : Homoscedasticity
3.0        26.0  18.0  13.547528333738724  50.099447343470956  0.5419011333495489   2.947026314321821  5.3416288641223115   0.0001298831037803705  0.9999350584481098  Reject005=0 : Heteroscedasticity
6.0        24.0  20.0  21.176825443839835   18.50627408469645  0.9207315410365146  0.9740144255103395  1.0486712921409913      0.9022130741564856  0.5488934629217572    Reject005=1 : Homoscedasticity
8.0        26.0  18.0  10.208326279272452   62.68477684515813  0.4083330511708981  3.6873398144210667    8.86968883910728  1.0677919595192265e-06  0.9999994661040202  Reject005=0 : Heteroscedasticity
...         ...   ...                 ...                 ...                 ...                 ...                 ...                     ...                 ...                               ...
988.0      24.0  20.0   32.44404447169466  39.875485807078434  1.4106106292041156  2.0987097793199174  1.4748649173576578      0.3613744283807254  0.8193127858096373    Reject005=1 : Homoscedasticity
990.0      25.0  19.0  24.117758939881515  27.968321815454075  1.0049066224950631  1.5537956564141153  1.5258641374233644     0.31924191494626086  0.8403790425268696    Reject005=1 : Homoscedasticity
992.0      23.0  21.0   84.84867759138208   85.68868694505508  3.8567580723355492   4.284434347252754  1.1060810484887003      0.8101952469292362  0.5949023765353819    Reject005=1 : Homoscedasticity
993.0      30.0  14.0  60.590133600338625   72.69280194227584  2.0893149517358145    5.59175399555968  2.5708854003159813     0.02938039975038209   0.985309800124809  Reject005=0 : Heteroscedasticity
997.0      21.0  23.0  23.114947966271117   27.78801567916788  1.1557473983135558  1.2630916217803583  1.0976302662111488      0.8343915181388373  0.5828042409305814    Reject005=1 : Homoscedasticity

[501 rows x 10 columns]

In [9]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
two_tailed_new=pd.DataFrame({"Replicate":list_replicate, "df0":list_df0, "df1":list_df1, "SSR0":list_SSR0,
                     "SSR1":list_SSR1, "MSE0":list_MSE0, "MSE1":list_MSE1,
                     "GQ_test_clusters":list_GQ_test_clusters, "two_tailed":list_two_tailed, "greater":list_p_greater})
two_tailed_new.set_index(['Replicate'], inplace=True)

two_tailed_new["two_tailed_new"]=two_tailed_new[["two_tailed","greater"]].apply(lambda value: value[0] if value[0]<0.5 else 2*value[1], axis=1)
two_tailed_new["Result_test"]=two_tailed_new["two_tailed_new"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                      if p_value < alpha else 'Reject005=1 : Homoscedasticity')


two_tailed_new_show=two_tailed_new.drop(columns=["two_tailed", "greater"])
two_tailed_new_show.astype(str)

            df0   df1                SSR0                SSR1                 MSE0                MSE1     GQ_test_clusters          two_tailed_new                       Result_test
Replicate
0.0        13.0  31.0  14.510139012294935   67.26230121007926   1.2091782510245779  2.2420767070026417   1.9439353028454083     0.20355166206881714    Reject005=1 : Homoscedasticity
1.0        28.0  16.0  39.808734119667854  28.953247694577996   1.4743975599876984  1.9302165129718665   1.2727906221081877      1.4406204480987648    Reject005=1 : Homoscedasticity
2.0        15.0  29.0  50.742124264283746   16.67012754156344    3.624437447448839    0.59536169791298  0.16992744958741926  4.7226597175171514e-05  Reject005=0 : Heteroscedasticity
3.0        26.0  18.0  13.547528333738724  50.099447343470956   0.5419011333495489   2.947026314321821   5.3416288641223115   0.0001298831037803705  Reject005=0 : Heteroscedasticity
4.0        22.0  22.0    167.503990525198   43.67372609291215   7.9763805011999045   2.079701242519626  0.26073245154324975   0.0025999587332257213  Reject005=0 : Heteroscedasticity
...         ...   ...                 ...                 ...                  ...                 ...                  ...                     ...                               ...
995.0      29.0  15.0   84.06996387560545   15.25258812876954    3.002498709843052  1.0894705806263958   0.3507594828110907     0.03598947151478133  Reject005=0 : Heteroscedasticity
996.0      15.0  29.0   41.30918196943066  18.557482727771955    2.950655854959333  0.6627672402775698   0.2323623345953408   0.0007512111589032389  Reject005=0 : Heteroscedasticity
997.0      21.0  23.0  23.114947966271117   27.78801567916788   1.1557473983135558  1.2630916217803583   1.0976302662111488      1.1656084818611627    Reject005=1 : Homoscedasticity
998.0      28.0  16.0  23.784602948243762  10.082671663040584   0.8809112203053245  0.6721781108693723    0.741852846932805      0.5383112720234026    Reject005=1 : Homoscedasticity
999.0      17.0  27.0   6.538680740700409   6.611350380730168  0.40866754629377555  0.2542827069511603    0.636627212223386     0.28635505976229736    Reject005=1 : Homoscedasticity

[1000 rows x 9 columns]

In [10]:
two_tailed_new_show['Result_test'].value_counts()

Reject005=1 : Homoscedasticity      520
Reject005=0 : Heteroscedasticity    480
Name: Result_test, dtype: int64